import { FileText, Sparkles, ThumbsUp, TriangleAlert } from "lucide-react";

const STEPS = [
  {
    icon: FileText,
    title: "We read the policy",
    body:
      "We pull each app's full privacy policy and terms — often thousands of words at a postgrad reading level — and parse every claim.",
  },
  {
    icon: Sparkles,
    title: "We rate by category",
    body:
      "Every permission gets a Safe / Caution / Risky / Dangerous rating with a plain-English explanation and a quote from the actual policy.",
  },
  {
    icon: ThumbsUp,
    title: "You decide before installing",
    body:
      "One number, one verdict, and the specific red flags — so you know what you're agreeing to in 30 seconds, not 30 minutes.",
  },
];

export function HowItWorks() {
  return (
    <section className="mt-12 sm:mt-20">
      <div className="mb-4 sm:mb-6">
        <h2 className="text-xl font-semibold tracking-tight text-ink sm:text-2xl">How it works</h2>
        <p className="mt-1 text-xs text-ink-muted sm:text-sm">
          The average privacy policy is 4,000 words long. We turn it into a sentence.
        </p>
      </div>
      <div className="grid gap-3 sm:gap-4 md:grid-cols-3">
        {STEPS.map((step, i) => {
          const Icon = step.icon;
          return (
            <div
              key={step.title}
              className="rounded-xl border border-line bg-surface p-4 sm:rounded-2xl sm:p-6"
            >
              <div className="flex items-center gap-3">
                <span className="flex h-9 w-9 items-center justify-center rounded-lg bg-brand/10 text-brand">
                  <Icon className="h-5 w-5" />
                </span>
                <span className="text-xs font-semibold uppercase tracking-wider text-ink-subtle">
                  Step {i + 1}
                </span>
              </div>
              <h3 className="mt-4 text-lg font-semibold text-ink">{step.title}</h3>
              <p className="mt-2 text-sm leading-relaxed text-ink-muted">{step.body}</p>
            </div>
          );
        })}
      </div>

      <div className="mt-3 rounded-xl border border-caution-line bg-caution-soft px-4 py-4 sm:mt-4 sm:rounded-2xl sm:px-6 sm:py-5">
        <div className="flex items-center gap-2">
          <TriangleAlert className="h-4 w-4 flex-shrink-0 text-caution-ink" />
          <h3 className="text-sm font-semibold text-caution-ink">AI interpretation - not legal advice</h3>
        </div>
        <p className="mt-2 text-sm leading-relaxed text-caution-ink/80">
          Ratings are generated by an AI reading publicly available privacy policies and terms sourced from the App Store listing and developer websites. They reflect how the policy is written - not how the app actually behaves. Always read the original policy before making privacy-sensitive decisions.
        </p>
      </div>
    </section>
  );
}
